# D:\gwkim\git\k8s-nifi-loki-prometheus-stack\k8s\nifi-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nifi-role
  namespace: flowkube-jobs
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nifi-rolebinding
  namespace: flowkube-jobs
subjects:
- kind: ServiceAccount
  name: nifi-sa
  namespace: flowkube-admin
roleRef:
  kind: Role
  name: nifi-role
  apiGroup: rbac.authorization.k8s.io